/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Layout: typeof import('./components/layout/index.vue')['default']
    Login: typeof import('./components/login.vue')['default']
    Logistic: typeof import('./views/logistic/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabViews: typeof import('./components/tab-views.vue')['default']
    Talk: typeof import('./views/talk/index.vue')['default']
    Toilet: typeof import('./views/toilet/index.vue')['default']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
