/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Admin: typeof import('./views/admin/index.vue')['default']
    AdminTabViews: typeof import('./views/admin/admin-tab-views/index.vue')['default']
    BreakdownDetail: typeof import('./views/admin/breakdown-detail/index.vue')['default']
    BreakdownEdit: typeof import('./views/admin/breakdown-list/breakdown-edit.vue')['default']
    BreakdownItem: typeof import('./views/admin/breakdown-list/breakdown-item.vue')['default']
    BreakdownList: typeof import('./views/admin/breakdown-list/index.vue')['default']
    FloorPicker: typeof import('./components/picker/floor-picker.vue')['default']
    GenderPicker: typeof import('./components/picker/gender-picker.vue')['default']
    Help: typeof import('./views/logistic/help/index.vue')['default']
    Info: typeof import('./views/logistic/info/index.vue')['default']
    Introduction: typeof import('./views/logistic/introduction/index.vue')['default']
    Layout: typeof import('./components/layout/index.vue')['default']
    Login: typeof import('./components/login.vue')['default']
    Logistic: typeof import('./views/logistic/index.vue')['default']
    LogisticHome: typeof import('./views/logistic/logistic-home.vue')['default']
    LogisticList: typeof import('./components/logistic/logistic-list.vue')['default']
    MaintainTitle: typeof import('./components/logistic/maintain-title.vue')['default']
    MenFloor: typeof import('./views/toilet/men-toilet/men-floor.vue')['default']
    MenToilet: typeof import('./views/toilet/men-toilet/index.vue')['default']
    PageHeader: typeof import('./components/page-header.vue')['default']
    Pit: typeof import('./views/toilet/pit.vue')['default']
    PopupPicker: typeof import('./components/logistic/popup-picker.vue')['default']
    Repair: typeof import('./views/logistic/repair/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/svg-icon/index.vue')['default']
    TabViews: typeof import('./components/tab-views.vue')['default']
    Talk: typeof import('./views/talk/index.vue')['default']
    TalkContent: typeof import('./views/talk/talk-content/index.vue')['default']
    TalkHeader: typeof import('./views/talk/talk-header/index.vue')['default']
    TempCodeRunnerFile: typeof import('./views/talk/talk-content/tempCodeRunnerFile.vue')['default']
    Toilet: typeof import('./views/toilet/index.vue')['default']
    VanBadge: typeof import('vant/es')['Badge']
    VanButton: typeof import('vant/es')['Button']
    VanDialog: typeof import('vant/es')['Dialog']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabber: typeof import('vant/es')['Tabber']
    VanUploader: typeof import('vant/es')['Uploader']
    WomenFloor: typeof import('./views/toilet/women-toilet/women-floor.vue')['default']
    WomenToilet: typeof import('./views/toilet/women-toilet/index.vue')['default']
  }
}
